/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Card: typeof import('./src/components/Product/Card.vue')['default']
    Carousel: typeof import('./src/components/Product/Carousel.vue')['default']
    Description: typeof import('./src/components/Product/Description.vue')['default']
    HeatMap: typeof import('./src/components/Charts/HeatMap.vue')['default']
    HeatMapChat: typeof import('./src/components/HeatMapChat.vue')['default']
    Info: typeof import('./src/components/Product/Info.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Product: typeof import('./src/components/Product/Product.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/Product/TopBar.vue')['default']
  }
}
